# Is is an example test file to evaluate the simulation
[dataset]
name = "Test"

[substrate]
E = 50000.0 # 50 kPa
nu = 0.45

[image]
micronsPerPixel=0.5 ##0.16 # µm
layerDistance=0.5

[simulation]
numberOfLayers= 20
xyPix = 512
NBeads =1e6

[adheasion.dipole]
# 1Pa*µm^2 = 10^(-12)Pa*m^2 = 10^(-12) N = 10^(-6)nN
type = "dipole"
F = 1e7 # 10 µN Total force per adheasion site
d = 20  # 20 µm Distance between counteracting adheasion sites
phi = 45 # 45 degree angle
a = 8   #  8 µm Size of adheasion site
pos = [0,0]
