# This describes the simple Hertz indentor
[dataset]
name = "hertzIndentor"

[substrate]
E = 10.0 # kPa
E_unit = "kPa"
nu = 0.45

[image]
spacing_xy = 0.8 # µm
spacing_z = 2.0 # µm

# micronsPerPixel=0.1 # µm
# layerDistance=0.25 # µm

[simulation]
n_points_xy = 128
n_points_z = 10

# numberOfLayers= 80
# xyPix = 1024

[adheasion.hertzIndentor]
type = "indentor"
F = 10 # µN Total force per adheasion site
F_unit = "µN"
a = 20  # 20 µm Distance between counteracting adheasion sites
pos = [0,0] # Dipole center (µm,µm)
