# This describes a structure with two overlapping elements
[dataset]
name = "hertzPull"

[substrate]
E = 3.0 # kPa
E_unit = "kPa"
nu = 0.45

[image]
micronsPerPixel=0.1 # µm
layerDistance=0.25

[simulation]
# This information 
numberOfLayers= 80
xyPix = 2048
NBeads =1e6 # Not used for TFM only simulations

[adheasion.pull]
type = "indentor"
F = -1 # µN Total force per adheasion site
F_unit = "µN"
a = 50  # 20 µm Distance between counteracting adheasion sites
pos = [25,25] # Dipole center (µm,µm)

[adheasion.push]
type = "indentor"
F = 1 # µN Total force per adheasion site
F_unit = "µN"
a = 50  # 20 µm Distance between counteracting adheasion sites
pos = [-25,-25] # Dipole center (µm,µm)
