# This describes the situation with 4 adheasion sites
[dataset]
name = "hertzQuadropole"

[substrate]
E = 50000.0 # = 50 kPa
nu = 0.45

[image]
micronsPerPixel=0.1 # µm
layerDistance=0.5

[simulation]
numberOfLayers= 32
xyPix = 512

[adheasion.left]
type = "dipole"
F = 0.01 # µN Total force per adheasion site
d = 20  # µm Distance between counteracting adheasion sites
phi = 110 # degrees angle
a = 2   # µm radius of adheasion site
pos = [0,0]

[adheasion.right]
type = "dipole"
F = 0.01 # µN Total force per adheasion site
d = 20  # µm Distance between counteracting adheasion sites
phi = 70 # degrees angle
a = 2   # µm radius of adheasion site
pos = [0,0]
